modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ssblur/unfocused-new_in_box/issues"
license = "CC0-1.0"

[[mods]]
modId = "new_in_box"
version = "${version}"
displayName = "New In Box"
authors = "SSBlur"
description = '''
An uninitialized Unfocused mod
'''
logoFile = "icon.png"

[[dependencies.new_in_box]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.new_in_box]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.new_in_box]]
modId = "unfocused"
type = "required"
versionRange = "[${unfocused_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "new_in_box.mixins.json"
